{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audit-anchor.secretName" . }}
  labels:
    {{- include "audit-anchor.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}

type: Opaque
stringData:
  DATABASE_URL: {{ required "secret.databaseUrl is required" .Values.secret.databaseUrl | quote }}
  PLATFORM_ADMIN_API_KEY: {{ required "secret.platformAdminApiKey is required" .Values.secret.platformAdminApiKey | quote }}
  HEDERA_TOPIC_ID: {{ required "secret.hederaTopicId is required" .Values.secret.hederaTopicId | quote }}
{{- end }}
